/**
 * คัดลอก CSS ของ Liyon-Theme เข้า src/shared/styles/liyon/ (generated ห้ามแก้มือ)
 * 1) ตัด @import url()  2) ตัด @media (prefers-color-scheme:dark) เพราะปิด enableSystem
 * 3) "Sarabun"/"Inter" → var(--font-*)  4) ล้มถ้าชื่อคลาสชน utility ของ Tailwind
 * ใช้: npm run sync:liyon  (LIYON_THEME_DIR override ต้นทางได้)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const LIYON_FILES = [
  "liyon-palettes.css",
  "liyon-base.css",
  "liyon-glass.css",
  "liyon-shell.css",
  "liyon-compat.css",
  "liyon-auth.css",
  "liyon-admin.css",
  "liyon-pages.css",
] as const;

export const RESERVED_CLASS_NAMES = new Set([
  "flex", "grid", "hidden", "block", "inline", "contents", "table", "container", "italic",
  "underline", "truncate", "border", "rounded", "shadow", "transition", "relative", "absolute",
  "fixed", "sticky", "static", "visible", "invisible", "collapse", "uppercase", "lowercase",
  "capitalize", "resize", "grow", "shrink", "ring", "outline", "blur", "filter", "prose",
  "group", "peer", "isolate", "antialiased", "overline", "ordinal", "transform",
  "flow-root", "inline-block", "inline-flex", "inline-grid", "sr-only", "not-sr-only",
  "list-none", "list-disc", "list-decimal", "normal-case", "overflow-hidden", "overflow-auto",
  "rounded-full", "will-change", "touch-none", "select-none", "pointer-events-none",
  "line-clamp-none", "backdrop-blur", "drop-shadow", "grayscale", "invert", "sepia",
]);
const ALLOWED = new Set(["dark"]);

export function stripImports(css: string): string {
  return css.replace(/^@import\s+url\([^)]*\);[^\n]*\n?/gm, "");
}

export function stripPrefersDark(css: string): string {
  const re = /@media\s*\(\s*prefers-color-scheme\s*:\s*dark\s*\)\s*\{/g;
  let out = "";
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css))) {
    out += css.slice(last, m.index);
    let depth = 1;
    let i = m.index + m[0].length;
    while (i < css.length && depth > 0) {
      if (css[i] === "{") depth++;
      else if (css[i] === "}") depth--;
      i++;
    }
    if (css[i] === "\n") i++;
    last = i;
    re.lastIndex = i;
  }
  return out + css.slice(last);
}

export function rewriteFontLiterals(css: string): string {
  return css
    .replace(/(?<!var\(--font-sarabun,\s*)"Sarabun"/g, 'var(--font-sarabun,"Sarabun")')
    .replace(/(?<!var\(--font-inter,\s*)"Inter"/g, 'var(--font-inter,"Inter")');
}

export function transform(css: string): string {
  return rewriteFontLiterals(stripPrefersDark(stripImports(css)));
}

export function collectClassNames(css: string): Set<string> {
  const noComments = css.replace(/\/\*[\s\S]*?\*\//g, "");
  const noStrings = noComments.replace(/"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'/g, '""');
  const names = new Set<string>();
  for (const chunk of noStrings.split("{")) {
    const selector = chunk.slice(chunk.lastIndexOf("}") + 1);
    for (const m of selector.matchAll(/\.(-?[_a-zA-Z][\w-]*)/g)) names.add(m[1]);
  }
  return names;
}

export function findCollisions(names: Iterable<string>): string[] {
  return [...names].filter((n) => RESERVED_CLASS_NAMES.has(n) && !ALLOWED.has(n)).sort();
}

function main(): void {
  const root = resolve(fileURLToPath(import.meta.url), "../..");
  const src = process.env.LIYON_THEME_DIR || "/Users/jira/Liyon-Theme/css";
  const dest = join(root, "src/shared/styles/liyon");
  mkdirSync(dest, { recursive: true });
  const all = new Set<string>();
  const outputs: Array<[string, string]> = [];
  for (const file of LIYON_FILES) {
    const css = transform(readFileSync(join(src, file), "utf8"));
    for (const n of collectClassNames(css)) all.add(n);
    outputs.push([file, `/* GENERATED by scripts/sync-liyon-theme.ts from ${file} — ห้ามแก้ไฟล์นี้ แก้ที่ Liyon-Theme แล้วรัน npm run sync:liyon */\n` + css]);
  }
  const collisions = findCollisions(all);
  if (collisions.length) {
    console.error(`ชื่อคลาสของ Liyon ชนกับ utility ของ Tailwind: ${collisions.join(", ")}`);
    process.exit(1);
  }
  for (const [file, content] of outputs) writeFileSync(join(dest, file), content);
  console.log(`sync แล้ว ${outputs.length} ไฟล์ → ${dest} (คลาส ${all.size} ชื่อ)`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
